config/routes.rb
ParasquidCs2066::Application.routes.draw do
  root :to => 'home#index'
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :matches
  resources :users

  namespace :api do
    api version: 1 do
      namespace 'industry' do
        get "offerings"
        get "needs"
      end
      resources :users do
        # change the route restrictions as needed
        resources :needs, only: [:get]
        resources :offerings, only: [:get]
        member do 
          get 'matches'
          scope '/meetings' do
            get 'upcoming'
            get 'past'
          end
        end
      end
    end
  end

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <!-- COPYRIGHTS -->
    <p class="pull-left">Typica - Bootstrap template crafted with passion</p>
    <p class="pull-right"><a href="#">Back to top</a></p>
  </div>
</footer>

app/views/layouts/_front_page_signed_out.html.erb
  <!-- TESTIMONIALS 3col -->
  <div class="row testimonials">
      <div class="span4">
        <%= image_tag 'img/testimonials_placeholder.png' %>
        <h2>Lorem ipsum</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
      </div>
      <div class="span4">
        <%= image_tag 'img/testimonials_placeholder.png' %>
        <h2>Quis nostrud</h2>
        <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. </p>
      </div>
      <div class="span4">
        <%= image_tag 'img/testimonials_placeholder.png' %>
        <h2>Cupidatat non proident</h2>
        <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
  </div>

  <div class="section-title">
    <h2>Typica is fully featured HTML template based on Bootstrap</h2>
  </div>

  <!-- TESTIMONIALS 4col -->
  <div class="row testimonials">
      <div class="span3">
        <%= image_tag 'img/testimonials_placeholder.png' %>
        <h2>Lorem ipsum</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
      </div>
      <div class="span3">
        <%= image_tag 'img/testimonials_placeholder.png' %>
        <h2>Quis nostrud</h2>
        <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. </p>
      </div>
      <div class="span3">
        <%= image_tag 'img/testimonials_placeholder.png' %>
        <h2>Cupidatat non proident</h2>
        <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <div class="span3">
        <%= image_tag 'img/testimonials_placeholder.png' %>
        <h2>Quis nostrud</h2>
        <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. </p>
      </div>
  </div>
</div><!-- .container -->

 <div class="hero-unit">
   <div class="container">
     <div class="row">
       <div class="span12">
         <h1>Who are we?</h1>
       </div>
     </div>
   </div>
 </div>

<div class="container">
  <div class="team">

    <div class="row">

      <div class="span4 section-title horizontal-left">
        <h2>Team members <i class="icon-chevron-right"></i></h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
        <div class="btn btn-large pull-right">Know more &raquo;</div></p>
      </div>

      <div class="span8">
        <div class="row">
          <div class="span2 item">
            <div class="circle-thumbnail">
              <%= image_tag 'img/team/1.jpg' %>
            </div>
            <h2>Kathy Jackson</h2>
            <p>Incididunt ut labore et dolore magna aliqua.</p>
          </div>
          <div class="span2 item">
            <div class="circle-thumbnail">
              <%= image_tag 'img/team/2.jpg' %>
            </div>
            <h2>Erin Fields</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor. </p>
          </div>
          <div class="span2 item">
            <div class="circle-thumbnail">
              <%= image_tag 'img/team/3.jpg' %>
            </div>
            <h2>Steven Jones</h2>
            <p>Ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.</p>
          </div>
          <div class="span2 item">
            <div class="circle-thumbnail">
              <%= image_tag 'img/team/4.jpg' %>
            </div>
            <h2>Jan Kowalski</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
          </div>
        </div>
      </div>
    </div>

    
    
  </div>

app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "ParasquidCs2066" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= localstorage_shim %>
  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>

</head>

app/views/layouts/_hero_unit.html.erb
<div class="hero-unit">
  <div class="container">
    <div class="row">
      <div class="span12">
        <h1>Crafted with <strong class="pink">LOVE</strong></h1>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="index.html"><%= image_tag 'logo.png' %></a>
      <div class="nav-collapse">
        <ul class="nav pull-right">
          <li><a href="index.html">Home</a></li>
          <li><a href="about.html">About</a></li>
          <li><a href="portfolio.html">Portfolio</a></li>
          <li><a href="blog_fullwidth.html">Blog</a></li>
          <li><a href="pricing.html">Pricing</a></li>
          <li><a href="contact.html">Contact</a></li>
          <li><% if current_user %>
            <%= link_to "Sign out", signout_path %>
          <% else %>
            <%= link_to "Sign In", '/auth/linkedin' %>
          <% end %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_slider_block.html.erb
<div class="slider-block">

  <div id="myCarousel" class="carousel slide">
    <!-- Carousel items -->
    <div class="carousel-inner">
      <div class="active item">
        <%= image_tag 'img/slide_bg2.jpg' %>
        <div class="caption middle-left container">
          <p class="small white text-dark">Introducing</p>
          <p class="medium white text-pink">Bootstrap based template</p>
          <p class="large pink add-space">TYPICA</p>
          <p>
            <%= link_to '/auth/linkedin', :class => 'popup', data: { height: 584, width: 440 }  do %>
              <%= image_tag('signup_with_linkedin.png') %>
            <% end %>
          </p>
        </div>
    </div>
    <div class="item">
      <%= image_tag 'img/slide_bg1.jpg' %>
      <div class="caption bottom-right container">
        <p class="large pink add-space">Better carousel</p>
        <p class="small white">Multiple text & background colors</p>
        <p class="small white">Multiple caption positions</p>
        <p class="medium white text-pink">and much more!</p>
      </div>
    </div>
    <div class="item">
      <%= image_tag 'img/slide_bg3.jpg' %>
      <div class="caption top-right container">
        <p class="medium pink add-space">Isn't that just</p>
        <p class="large white text-dark">AWESOME?</p>
      </div>
    </div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <%= render 'layouts/head' %>

  <body>

    <%= render 'layouts/navbar' %>

    <div class="container main">

      <%= yield %>

    </div> <!-- /container -->

    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/layouts/application_signed_out.html.erb
<!DOCTYPE html>
<html lang="en">

  <%= render 'layouts/head' %>

  <body>

    <%= render 'layouts/navbar' %>

    <%= render 'layouts/slider_block' %>

    <%= render 'layouts/hero_unit' %>

    <div class="container">

      <%= render 'layouts/front_page_signed_out' %>

    </div> <!-- /container -->

    <%= render 'layouts/footer' %>

  </body>
</html>